server:
  port: 8082

spring:
  application:
    name: inventory system
  datasource:
    url: jdbc:mysql://localhost:3306/inventory
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        ddl-auto: none
        naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog-master.yml
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: inventory-group1



logging:
  level:
    org.hibernate: info
    org.hibernate.Sql: debug

